name: Build connector

on:
  workflow_dispatch:
    inputs:
      metabase-version:
        required: true
        description: Metabase version to compile with
        type: string
        default: v0.46.2

jobs:
  build-connector:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Metabase Code"
        uses: actions/checkout@v2
        with:
          repository: metabase/metabase
          ref: ${{ github.event.inputs.metabase-version }}
          path: metabase

      - name: "Checkout Driver"
        uses: actions/checkout@v2
        with:
          repository: Baoqi/metabase-dremio-driver
          path: metabase-dremio-driver

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.7
        if: steps.cache-metabase-jar.outputs.cache-hit != 'true'
        with:
          # Install just one or all simultaneously
          cli: 'latest' # Clojure CLI based on tools.deps

      - name: "Run build.sh"
        run: |
          cd metabase-dremio-driver && ./build.sh

      - name: "debug folder structure"
        run: |
          echo $(pwd)
          ls -lah ./
          ls -lah ../
          ls -lah ./target/
